language: node_js

node_js:
  - '8.11'

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

cache: yarn

script:
  - yarn
  - yarn run lint
  - |
    cat > .env.production << EOF
    CONTENTFUL_SPACE_ID='`$CONTENTFUL_SPACE_ID`'
    CONTENTFUL_ACCESS_TOKEN='`$CONTENTFUL_ACCESS_TOKEN`'
    EOF
  - yarn run build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    acl: public_read
    local_dir: 'public'
    skip_cleanup: true
    region: 'eu-central-1'
    on:
      branch: dev
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    acl: public_read
    local_dir: 'public'
    skip_cleanup: true
    region: 'eu-central-1'
    on:
      branch: master

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*"