[context.production.environment]
CONTENTFUL_ENVIRONMENT = "master"

# [context.campaign-launch]
# command = "npm run build-launch"

[context.campaign-launch.environment]
CONTENTFUL_ENVIRONMENT = "launch"
GATSBY_USE_DEV_BACKEND = "override"

# Tepmorary setup for the preview deploys 
# triggered by PRs to the campaign-launch branch
# Other build command hopefully not needed
# [context.deploy-preview]
# command = "npm run build-launch"

[context.deploy-preview.environment]
CONTENTFUL_ENVIRONMENT = "launch"
GATSBY_USE_DEV_BACKEND = "override"
