[context.production.environment]
CONTENTFUL_ENVIRONMENT = "master"

[context.campaign-launch]
command = "npm run build-dev-backend"

[context.campaign-launch.environment]
CONTENTFUL_ENVIRONMENT = "launch"
GATSBY_USE_DEV_BACKEND = "override"

[context.gemeinden-to-orte.environment]
CONTENTFUL_ENVIRONMENT = "2021-10-04"

[context.deploy-preview]
command = "npm run build-dev-backend"

[context.deploy-preview.environment]
CONTENTFUL_ENVIRONMENT = "2021-08-25"
GATSBY_USE_DEV_BACKEND = "override"

[[headers]]
  for = "/iframes/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"