name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 14.x

      - name: Install modules
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Check formating
        run: npm run prettier:check
